export class AuditLogErrorCode {
  public static AUDIT_LOG_ID_EMPTY = 'AUDIT_LOG_ID_EMPTY';
  public static AUDIT_LOG_ACTION_EMPTY = 'AUDIT_LOG_ACTION_EMPTY';
  public static AUDIT_LOG_MODULE_EMPTY = 'AUDIT_LOG_MODULE_EMPTY';
  public static AUDIT_LOG_RESOURCE_ID_EMPTY = 'AUDIT_LOG_RESOURCE_ID_EMPTY';
  public static AUDIT_LOG_PERFOMED_BY_EMPTY = 'AUDIT_LOG_PERFOMED_BY_EMPTY';
}
