export enum ErrorCode {
  // Shared code
  NAME_TOO_LONG = 'NAME_TOO_LONG',
  ID_TOO_LONG = 'ID_TOO_LONG',
  ID_EMPTY = 'ID_EMPTY',
  IS_EXISTS = 'IS_EXISTS',
  NOT_FOUND = 'NOT_FOUND',

  // Audit log
  AUDIT_LOG_ACTION_EMPTY = 'AUDIT_LOG_ACTION_EMPTY',
  AUDIT_LOG_MODULE_EMPTY = 'AUDIT_LOG_MODULE_EMPTY',
  AUDIT_LOG_RESOURCE_ID_EMPTY = 'AUDIT_LOG_RESOURCE_ID_EMPTY',
  AUDIT_LOG_PERFOMED_BY_EMPTY = 'AUDIT_LOG_PERFOMED_BY_EMPTY',
}
